### ISSUE TITLE
Adding actual and miss predicted labels to feature matrix

### ISSUE THREAD

**Issue by omeryasar** [zohreh-aaa/DNN#1]
Hi, 
First, Thanks for sharing your work.
In the paper diagram additional to extracted vgg16 features, miss predicted and actual labels also added to feature matrix. But in your repo I cant see the part that you add those info into feature matrix.

Can you explain me how to add those labels into feature matrix? Basicly extending each extracted feature by that 2 label? Or a different way?

Thanks in advance

**Comment by zohreh-aaa** [comment]
> Hi, First, Thanks for sharing your work. In the paper diagram additional to extracted vgg16 features, miss predicted and actual labels also added to feature matrix. But in your repo I cant see the part that you add those info into feature matrix.
> 
> Can you explain me how to add those labels into feature matrix? Basicly extending each extracted feature by that 2 label? Or a different way?
> 
> Thanks in advance

Hi,

Thanks for your comment!  There is a difference between the features extracted from VGG16 for fault definition and those extracted for calculating geometric diversity. For the fault definition part, we add two columns of y_true and predicted y, and scale them before adding to the matrix of VGG16 features. For geometric diversity calculation, we didn't do that since it is a black box method.

I have added new code that reimplements the fault definition part, allowing you to set different hyperparameters and then find the best clustering based on the best silhouette score.  ( You can find the code here: RQ2_3/Clustering/Fault_definition_(base_code).ipynb)
Hope it helps!

**Comment by omeryasar** [comment]
Thanks a lot for your quick response. I will work on it and it helped a lot. 
Have a great day.
